### PR TITLE
fix for #issue-15.

### PR DESCRIPTION
**Pull request by rbonifacio**
This patch moves the logic that makes the labels and
goto statements more user friendly, from the decompiler
Java class to a jimple-to-jimple transformation in
Rascal.

### CODE REVIEW

**Review by faustocarva — COMMENTED** [review]
Please test it with sample code in ControlStatements.java. I'm getting an the error bellow: 
```
      |project://JimpleFramework/src/main/rascal/lang/jimple/Decompiler.rsc|:10,0: Java("IllegalStateException","Label offset position has not been resolved yet")
        at org.objectweb.asm.Label.getOffset(|unknown:///UNKNOWN_FILENAME|(0,0,<0,0>,<0,0>))
        at lang.jimple.internal.Decompiler$InstructionSetVisitor.visitTableSwitchInsn(|unknown:///Decompiler.java|(0,0,<643,0>,<643,0>))
        at org.objectweb.asm.tree.TableSwitchInsnNode.accept(|unknown:///UNKNOWN_FILENAME|(0,0,<0,0>,<0,0>))
        at org.objectweb.asm.tree.InsnList.accept(|unknown:///UNKNOWN_FILENAME|(0,0,<0,0>,<0,0>))
        at lang.jimple.internal.Decompiler$GenerateJimpleClassVisitor.visitMethod(|unknown:///Decompiler.java|(0,0,<210,0>,<210,0>))
        at lang.jimple.internal.Decompiler$GenerateJimpleClassVisitor.visitEnd(|unknown:///Decompiler.java|(0,0,<162,0>,<162,0>))
        at org.objectweb.asm.ClassReader.accept(|unknown:///UNKNOWN_FILENAME|(0,0,<0,0>,<0,0>))
        at org.objectweb.asm.ClassReader.accept(|unknown:///UNKNOWN_FILENAME|(0,0,<0,0>,<0,0>))
        at lang.jimple.internal.Decompiler.decompile(|unknown:///Decompiler.java|(0,0,<111,0>,<111,0>))
```

**Review by faustocarva — COMMENTED** [review]
Something is wrong, we have labels all over the jimple output, look at this:
```
     L1519276923:
     
        if $i1 > $i2 goto L1898617072;
     
        goto L640850966;
     
     L1898617072:
     
     L640850966:

```

**Comment by faustocarva** [comment]
> Please test it with sample code in ControlStatements.java. I'm getting an the error bellow:
> 
> ```
>       |project://JimpleFramework/src/main/rascal/lang/jimple/Decompiler.rsc|:10,0: Java("IllegalStateException","Label offset position has not been resolved yet")
>         at org.objectweb.asm.Label.getOffset(|unknown:///UNKNOWN_FILENAME|(0,0,<0,0>,<0,0>))
>         at lang.jimple.internal.Decompiler$InstructionSetVisitor.visitTableSwitchInsn(|unknown:///Decompiler.java|(0,0,<643,0>,<643,0>))
>         at org.objectweb.asm.tree.TableSwitchInsnNode.accept(|unknown:///UNKNOWN_FILENAME|(0,0,<0,0>,<0,0>))
>         at org.objectweb.asm.tree.InsnList.accept(|unknown:///UNKNOWN_FILENAME|(0,0,<0,0>,<0,0>))
>         at lang.jimple.internal.Decompiler$GenerateJimpleClassVisitor.visitMethod(|unknown:///Decompiler.java|(0,0,<210,0>,<210,0>))
>         at lang.jimple.internal.Decompiler$GenerateJimpleClassVisitor.visitEnd(|unknown:///Decompiler.java|(0,0,<162,0>,<162,0>))
>         at org.objectweb.asm.ClassReader.accept(|unknown:///UNKNOWN_FILENAME|(0,0,<0,0>,<0,0>))
>         at org.objectweb.asm.ClassReader.accept(|unknown:///UNKNOWN_FILENAME|(0,0,<0,0>,<0,0>))
>         at lang.jimple.internal.Decompiler.decompile(|unknown:///Decompiler.java|(0,0,<111,0>,<111,0>))
> ```

@rbonifacio this is still happening, even with your recent changes.

**Comment by rbonifacio** [comment]
@faustocarva , I am not able to reproduce this error. Could you please share more details? Does this error occur when you run the decompiler, or after running a specific analysis or transformation? 

I've just written this test case and it is passing. 

```java
        @Test 
	public void decompileControlStatements() {
		try {
			File classFile = new File("./target/test-classes/samples/ControlStatements"); 			
			assertNotNull(classFile);
			
			IValueFactory vf = ValueFactory.getInstance();
			Decompiler decompiler = new Decompiler(vf);
			IConstructor c = decompiler.decompile(new FileInputStream(classFile), null);
			
			assertNotNull(c);
		}
		catch(Exception e) {
			e.printStackTrace();
			fail(e.getLocalizedMessage());
		}
	}
```

**Comment by rbonifacio** [comment]
@faustocarva , could you please run the tests from the command line? I think that I reproduced the error, and it was occurring because the ControlStatements java file had not been compiled via Eclipse.

**Review by faustocarva — APPROVED** [review]
Now it's all working pretty fine. We still have to decide where the "jimpfly labels" should be placed. But the overall PR it's all fine.

**Pull request merged**
